apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-server
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: kube-server
    spec:
      containers:
      - image: dileep5885/kube-server
        imagePullPolicy: Always
        name: kube-server
        ports:
        - containerPort: 8080