apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: kube-frontend
spec:
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate:
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: kube-frontend                                  # 6
    spec:
      containers:
      - image: dileep5885/kube-frontend
        imagePullPolicy: Always                         # 7
        name: kube-frontend
        ports:
        - containerPort: 80